{% set name = "jenkins-job-builder" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0c3fc607224c43aa33ec518bfa44e9ae4707063333e9b15091c3181add77585

build:
  noarch: python
  number: 0
  script: "python -m pip install . -vv"
  
requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9.0
    - pyyaml >=3.10.0,<6
    - pbr >=1.8
    - stevedore >=1.17.1
    - python-jenkins >=0.4.15
    - fasteners
    - jinja2
    
test:
  imports:
    - jenkins-job-builder
    - jenkins-jobs --help

about:
  home: https://opendev.org/jjb/jenkins-job-builder
  license: Apache-2.0
  license_file: COPYING
  summary: 'Jenkins Job Builder takes simple descriptions of Jenkins jobs in YAML or JSON format and uses them to configure Jenkins'

extra:
  recipe-maintainers:
    - ThejashwiniSwamy